#define TOK_OROR                            1
#define TOK_ANDAND                          2
#define TOK_EQ                              3
#define TOK_NEQ                             4
#define TOK_LT                              5
#define TOK_LE                              6
#define TOK_GT                              7
#define TOK_GE                              8
#define TOK_PLUS                            9
#define TOK_MINUS                          10
#define TOK_OR                             11
#define TOK_XOR                            12
#define TOK_DIVIDE                         13
#define TOK_TIMES                          14
#define TOK_MOD                            15
#define TOK_SHIFTL                         16
#define TOK_SHIFTR                         17
#define TOK_AND                            18
#define TOK_ANDNOT                         19
#define TOK_IDENT                          20
#define TOK_ASSIGN                         21
#define TOK_INT                            22
#define TOK_FLOAT                          23
#define TOK_STRING                         24
#define TOK_CHAR                           25
#define TOK_COMMA                          26
#define TOK_SEMICOLON                      27
#define TOK_DECLARIZE                      28
#define TOK_A_DIVIDE                       29
#define TOK_A_TIMES                        30
#define TOK_A_MOD                          31
#define TOK_A_SHIFTL                       32
#define TOK_A_SHIFTR                       33
#define TOK_A_AND                          34
#define TOK_A_ANDNOT                       35
#define TOK_A_PLUS                         36
#define TOK_A_MINUS                        37
#define TOK_A_OR                           38
#define TOK_A_XOR                          39
#define TOK_INC                            40
#define TOK_DEC                            41
#define TOK_BREAK                          42
#define TOK_CONTINUE                       43
#define TOK_FALLTHROUGH                    44
#define TOK_RETURN                         45
#define TOK_IF                             46
#define TOK_ELSE                           47
#define TOK_FOR                            48
#define TOK_SWITCH                         49
#define TOK_LCURLY                         50
#define TOK_RCURLY                         51
#define TOK_CASE                           52
#define TOK_COLON                          53
#define TOK_DEFAULT                        54
#define TOK_IMPORT                         55
#define TOK_LPAREN                         56
#define TOK_RPAREN                         57
#define TOK_TYPE                           58
#define TOK_CONST                          59
#define TOK_VAR                            60
#define TOK_FUNC                           61
#define TOK_LSB                            62
#define TOK_RSB                            63
#define TOK_DOT                            64
#define TOK_STRUCT                         65
#define TOK_UNION                          66
#define TOK_ELLIPSIS                       67
#define TOK_NOT                            68
