#define TOK_OROR                            1
#define TOK_ANDAND                          2
#define TOK_EQ                              3
#define TOK_NEQ                             4
#define TOK_LT                              5
#define TOK_LE                              6
#define TOK_GT                              7
#define TOK_GE                              8
#define TOK_PLUS                            9
#define TOK_MINUS                          10
#define TOK_OR                             11
#define TOK_XOR                            12
#define TOK_DIVIDE                         13
#define TOK_TIMES                          14
#define TOK_MOD                            15
#define TOK_SHIFTL                         16
#define TOK_SHIFTR                         17
#define TOK_AND                            18
#define TOK_ANDNOT                         19
#define TOK_ASSIGN                         20
#define TOK_DECLARIZE                      21
#define TOK_A_DIVIDE                       22
#define TOK_A_TIMES                        23
#define TOK_A_MOD                          24
#define TOK_A_SHIFTL                       25
#define TOK_A_SHIFTR                       26
#define TOK_A_AND                          27
#define TOK_A_ANDNOT                       28
#define TOK_A_PLUS                         29
#define TOK_A_MINUS                        30
#define TOK_A_OR                           31
#define TOK_A_XOR                          32
#define TOK_INC                            33
#define TOK_DEC                            34
#define TOK_SEMICOLON                      35
#define TOK_BREAK                          36
#define TOK_CONTINUE                       37
#define TOK_FALLTHROUGH                    38
#define TOK_RETURN                         39
#define TOK_IF                             40
#define TOK_ELSE                           41
#define TOK_FOR                            42
#define TOK_SWITCH                         43
#define TOK_LCURLY                         44
#define TOK_RCURLY                         45
#define TOK_CASE                           46
#define TOK_COLON                          47
#define TOK_DEFAULT                        48
#define TOK_IMPORT                         49
#define TOK_LPAREN                         50
#define TOK_RPAREN                         51
#define TOK_TYPE                           52
#define TOK_CONST                          53
#define TOK_VAR                            54
#define TOK_FUNC                           55
#define TOK_IDENT                          56
#define TOK_STRING                         57
#define TOK_LSB                            58
#define TOK_RSB                            59
#define TOK_DOT                            60
#define TOK_STRUCT                         61
#define TOK_COMMA                          62
#define TOK_ELLIPSIS                       63
#define TOK_INT                            64
#define TOK_FLOAT                          65
#define TOK_CHAR                           66
#define TOK_NOT                            67
