def build(bld):
	compiler_src = bld.path.ant_glob("*.cpp cityhash/*.cc")
	rpath = []
	if bld.env.OPT_LENSTR:
		rpath = ['/usr/lib/llvm']
	bld.program(
		source   = compiler_src,
		target   = 'krawl',
		use      = 'LLVM',
		lib      = 'mpfr gmp',
		rpath    = rpath
	)
