FIND_PROGRAM(LLVM_CONFIG_EXECUTABLE llvm-config DOC "path to the llvm-config executable")
IF(LLVM_CONFIG_EXECUTABLE)
	EXEC_PROGRAM(${LLVM_CONFIG_EXECUTABLE} ARGS --version    OUTPUT_VARIABLE LLVM_STRING_VERSION )
	EXEC_PROGRAM(${LLVM_CONFIG_EXECUTABLE} ARGS --libdir     OUTPUT_VARIABLE LLVM_LIBRARY_DIRS_ )
	EXEC_PROGRAM(${LLVM_CONFIG_EXECUTABLE} ARGS --includedir OUTPUT_VARIABLE LLVM_INCLUDE_DIRS_ )
	EXEC_PROGRAM(${LLVM_CONFIG_EXECUTABLE} ARGS --cppflags   OUTPUT_VARIABLE LLVM_COMPILE_FLAGS )
	EXEC_PROGRAM(${LLVM_CONFIG_EXECUTABLE} ARGS --ldflags    OUTPUT_VARIABLE LLVM_LDFLAGS )
ENDIF()

SET(LLVM_INCLUDE_DIRS ${LLVM_INCLUDE_DIRS_} CACHE STRING "LLVM include path")
SET(LLVM_LIBRARY_DIRS ${LLVM_LIBRARY_DIRS_} CACHE STRING "LLVM library path")

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(LLVM DEFAULT_MSG LLVM_CONFIG_EXECUTABLE)
